### ISSUE TITLE
tase open issues

### ISSUE THREAD

**Issue by noamGross** [hyperledger-labs/private-transaction-families#19]
https://docs.google.com/document/d/13xcj3w0ULV85fpVXec275Vb7e8bOaBcVDUbBZJhmzZg/edit?usp=sharing

**Comment by duncanjw** [comment]
Issues reviewed and those related to this repo opened. Full list [here](https://docs.google.com/spreadsheets/d/12y2YM7f2Od6GWjcfUqpKN1FO0NfdrWTEEn3Da39V0oc/edit)

**Comment by duncanjw** [comment]
@yoni-wolf please close this issue

**Comment by duncanjw** [comment]
Or @noamGross please close it
