### ISSUE TITLE
Simplify packaging of privacy framework

### ISSUE THREAD

**Issue by duncanjw** [hyperledger-labs/private-transaction-families#21]

**Comment by yoni-wolf** [comment]
Commit 5be643487a8bc7db977a2a73c9d70a43a42241eb contains the new get_sources.sh
This new script is meant for users developing their own business logic that don't want to use git merge for updating to latest code.
The script will copy sawtooth cxx sdk, rest api and all src files except for business logic and config.cpp to a desired folder.

**Comment by duncanjw** [comment]
https://github.com/hyperledger-labs/private-transaction-families/blob/master/get_source.sh
