### ISSUE TITLE
Support decrypt requests

### ISSUE THREAD

**Issue by duncanjw** [hyperledger-labs/private-transaction-families#22]
Similar to read requests [here](https://github.com/hyperledger-labs/private-transaction-families/tree/master/Debug/client_reader) we would like the ability to request data decryption

**Comment by yoni-wolf** [comment]
commit 4570eb0 contains this code.
note also new example of read script - Debug/client_reader/read_request_new.py

the new script can get multiple addresses as arguments, and will first read the encrypted data directly from sawtooth rest api and add the addresses data to the decrypt request.
